### ISSUE TITLE
Error: Width must be multiple of 2!

### ISSUE THREAD

**Issue by ctjhoa** [rajasegar/eax#3]
Hi,

I get this error at every start. Not sure where it comes from.

```
Width must be multiple of 2!
(node:2632565) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_canvas' of undefined
    at Donut.Canvas.render (/home/ctjhoa/.npm/_npx/2632565/lib/node_modules/ember-app-explorer/node_modules/blessed-contrib/lib/widget/canvas.js:46:24)
    at /home/ctjhoa/.npm/_npx/2632565/lib/node_modules/ember-app-explorer/node_modules/blessed/lib/widgets/screen.js:738:8
    at Array.forEach (<anonymous>)
    at Screen.render (/home/ctjhoa/.npm/_npx/2632565/lib/node_modules/ember-app-explorer/node_modules/blessed/lib/widgets/screen.js:735:17)
    at exec.then.data (/home/ctjhoa/.npm/_npx/2632565/lib/node_modules/ember-app-explorer/src/pages/home.js:65:12)
    at <anonymous>
```

**Comment by rajasegar** [comment]
It comes from the `blessed-contrib` package I guess, let me take a look why ...

**Comment by rajasegar** [comment]
@ctjhoa Are you still getting this error with latest version?
Can you please verify and let me know

**Comment by ctjhoa** [comment]
Looks good now. Thanks!

**Comment by binarymist** [comment]
Still getting it when blessed is `spawn`ed. If you somehow fixed it @rajasegar how and what did you do?

Thanks.

**Comment by rajasegar** [comment]
@binarymist I don't exactly remember how I fixed it, meanwhile can you please let me know more details, like OS version, Node version, etc, Will give it a shot...

**Comment by binarymist** [comment]
Hi @rajasegar 

Linux Mint 18  
Node v14.15.0  
blessed "^0.1.81"  
blessed-contrib "^4.8.20"  

I debugged blessed-contrib and the width of the canvas is `-5`, height is `-12`. I'm figuring this is because blessed is being `spawn`ed from another process, so it doesn't have it's own terminal.

More details in my [issue](https://github.com/purpleteam-labs/purpleteam/issues/51).

Correct me if you think I'm wrong?

Thanks.
